### ISSUE TITLE
clash exporter如何使用？

### ISSUE THREAD

**Issue by BMSK1994** [zxh326/clash-exporter#11]
请问这里clash exporter和clash是怎么关联起来的呢，它是如何拿到clash的数据的？

**Comment by zxh326** [comment]
通过 clash 暴露的 API

https://dreamacro.github.io/clash/runtime/external-controller.html#restful-api-documentation

**Comment by BMSK1994** [comment]
> 通过 clash 暴露的 API
> 
> https://dreamacro.github.io/clash/runtime/external-controller.html#restful-api-documentation

大佬，是否只用在docker-compose.yml配置clash的Premium端口？我将CLASH_HOST从9090修改为其他值后，docker还在报错
collector: info failed error:  Get "http://127.0.0.1:9090/version":

**Comment by zxh326** [comment]
看报错访问的还是 9090 端口，确定改没改成功

**Comment by BMSK1994** [comment]
大佬，你写的这个工具好帅啊~我已经能展示流量了，想再请教你下：
1.只有clash-premiun下才能使用，普通clash不能使用，是这样吗？
2.它展示的仅仅是这个clash-premiun的流量情况吗？假设我在安卓clash（即另一个clash客户端）使用同样的订阅链接上网，这个部署在pc的clash-prenium会记录安卓的访问数据吗？

**Comment by zxh326** [comment]
> 1.只有clash-premiun下才能使用，普通clash不能使用，是这样吗？

都可以用，只是非 premium 版本会丢失 tracing 数据，就是 dashboard 中最后的数据

> 2.它展示的仅仅是这个clash-premiun的流量情况吗？假设我在安卓clash（即另一个clash客户端）使用同样的订阅链接上网，这个部署在pc的clash-prenium会记录安卓的访问数据吗？

跟订阅链接没有关系。仅抓取环境变量中提供的 CLASH_HOST 的 clash 的数据
