### ISSUE TITLE
startup error in pve debian12

### ISSUE THREAD

**Issue by shaonianche** [zxh326/clash-exporter#13]
I get the following error in the boot log, can you help me take a look?

`failed to dial: failed to WebSocket dial: expected handshake response status code 101 but got 404`

**Comment by zxh326** [comment]
What is the version of clash?

**Comment by shaonianche** [comment]
> What is the version of clash?

It has been tested in the following environments:
ShellClash: v1.8.1, clash core version: v1.7.1 
openclash: v0.45.152-beta, clash_tun: 2023.08.17-13-gdcc8d87

**Comment by zxh326** [comment]
> > What is the version of clash?
> 
> It has been tested in the following environments: ShellClash: v1.8.1, clash core version: v1.7.1 openclash: v0.45.152-beta, clash_tun: 2023.08.17-13-gdcc8d87

Can you try this command to see it works? 

btw, like [yacd](https://github.com/haishanh/yacd) dashboard tools work normally?

```sh
curl -v http://$CLASH_HOST/connections -H "Authorization: Bearer $CLASH_TOKEN"
```

**Comment by shaonianche** [comment]
> btw, like [yacd](https://github.com/haishanh/yacd) dashboard tools work normally?

yes

> ```shell
> curl -v http://$CLASH_HOST/connections -H "Authorization: Bearer $CLASH_TOKEN"
> ```

![image](https://github.com/zxh326/clash-exporter/assets/16186646/637ea3fd-5eeb-4f68-8a9b-3d4bbec9e6d3)

**Comment by zxh326** [comment]
I'm not sure what happened....

but I saw the CLASH_HOST environment after you ran the clash_exporter command, maybe it is not working.

**Comment by shaonianche** [comment]
> but I saw the CLASH_HOST environment after you ran the clash_exporter command, maybe it is not working.

oh！yes，the environment variable in the command line didn't take effect, when I exported it to the system it ran successfully ...
