### ISSUE TITLE
时间过滤似乎失效

### ISSUE THREAD

**Issue by Skylarzz** [zxh326/clash-exporter#14]
选择 Last 5 minutes 只影响 Overview 的折线图，对其它部分没有改变
选择一个时间段，出现的数据也比较混乱

非常好的项目
@zxh326 可以修复下吗

![图片](https://github.com/zxh326/clash-exporter/assets/14090545/38d8f33d-af44-45be-94c4-6a6100087fc2)

**Comment by zxh326** [comment]
你是指下面的总流量吗

**Comment by Skylarzz** [comment]
> 你是指下面的总流量吗

就是右上角可以选择 time range，我的理解是选择时间区间后下面的数据就只统计区间内的数据
大部分数据似乎都没有按照预期的工作，比如总下载量、总上传量、客户端总流量、代理总流量这些
选择 Last 5 minutes 感受最明显，数据量应该会小很多，但版面的内容几乎没有变化的

**Comment by zxh326** [comment]
> > 你是指下面的总流量吗
> 
> 就是右上角可以选择 time range，我的理解是选择时间区间后下面的数据就只统计区间内的数据 大部分数据似乎都没有按照预期的工作，比如总下载量、总上传量、客户端总流量、代理总流量这些 选择 Last 5 minutes 感受最明显，数据量应该会小很多，但版面的内容几乎没有变化的

对 这里的总 就是总的意思（开始收集以来的总流量），没有按 range 算。 这么做的一方面考虑是 metrics 量太大了，会给 prometheus 带来不小的压力。所以用的都是瞬时的总流量。

不过数据都是有的，你可以尝试自己画一个。比如目的地总流量可以改这这样即可。

```
topk(10, sort_desc(sum by (destination) (increase(clash_network_traffic_bytes_total{source=~"$source", policy=~"$policy",type=~"$type"}[$__range]))))
```

**Comment by Skylarzz** [comment]
感谢帮助
