### ISSUE TITLE
D大小号？D大原来做过这玩意但是当时它支持P核，这个也是只支持P核吗

### ISSUE THREAD

**Issue by lauren12133** [zxh326/clash-exporter#15]
D大小号？D大原来做过这玩意但是当时它支持P核，这个也是只支持P核吗

**Comment by zxh326** [comment]
> D大小号？D大原来做过这玩意但是当时它支持P核，这个也是只支持P核吗

不是。。。。都支持，非 P核的话 部分数据是空的

**Comment by zcbxxx1** [comment]
> > D大小号？D大原来做过这玩意但是当时它支持P核，这个也是只支持P核吗
> 
> 不是。。。。都支持，非 P核的话 部分数据是空的

现在的meta核行不行？openclash里好像没有tracing选项
