### ISSUE TITLE
Some data appears to be missing?

### ISSUE THREAD

**Issue by luckyyyyy** [zxh326/clash-exporter#3]
<img width="1920" alt="image" src="https://github.com/zxh326/clash-exporter/assets/9210430/9a655408-ec82-4a9b-829a-7c5f76e84d9d">

**Comment by zxh326** [comment]
check prometheus config 

https://github.com/zxh326/clash-exporter/blob/5be7882ddcd3061c6838e324807d9ba977e627bd/prometheus/record.rules.yml#L1-L5

https://github.com/zxh326/clash-exporter/blob/5be7882ddcd3061c6838e324807d9ba977e627bd/prometheus/prometheus.yml#L12-L13

**Comment by luckyyyyy** [comment]
> check prometheus config
> 
> https://github.com/zxh326/clash-exporter/blob/5be7882ddcd3061c6838e324807d9ba977e627bd/prometheus/record.rules.yml#L1-L5
> 
> https://github.com/zxh326/clash-exporter/blob/5be7882ddcd3061c6838e324807d9ba977e627bd/prometheus/prometheus.yml#L12-L13

same configuration content

**Comment by zxh326** [comment]
能打开 Prometheus ，然后看看 `source_policy_type:clash_network_traffic_bytes_total:sum` 是否有数据吗。

刚看到 你的 dns 也是空的，检查一下 tracing 是否开启。

> tracing metrics is empty
> Required clash premium version
> Follow [clash profile docs](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#tracing) enable profile tracing
> Add -collectTracing=true flag in clash-exporter start script

**Comment by luckyyyyy** [comment]
> 

<img width="1325" alt="image" src="https://github.com/zxh326/clash-exporter/assets/9210430/4be2a0fe-729e-4e79-b665-9cc6e43e59ed">


这样？

profile:
  store-selected: true
  store-fake-ip: true
  tracing: true

确定开了的 版本是 

<img width="130" alt="image" src="https://github.com/zxh326/clash-exporter/assets/9210430/133c7c9f-1684-443c-a334-7a6326e4ed6c">

**Comment by luckyyyyy** [comment]
测试了下作者提供的 是有数据的

<img width="1316" alt="image" src="https://github.com/zxh326/clash-exporter/assets/9210430/dc0d2c94-c227-45cf-8f42-c0c2c644e2a8">

**Comment by zxh326** [comment]
### dns 或者最下面 的 tracing 数据为空
- clash 开启 profile.tracing
- clash-export 启动的时候加上 `-collectTracing=true`


### 中间的 Traffic statistics 数据为空

- 检查下 Prometheus 的配置
- 看下是否有 
`source_policy_type:clash_network_traffic_bytes_total:sum` metrics 

<img width="1161" alt="image" src="https://github.com/zxh326/clash-exporter/assets/21299255/95c99bab-d24c-4ea7-803b-572735aa8b9d">

**Comment by Dark-Existed** [comment]
<img width="1692" alt="image" src="https://github.com/zxh326/clash-exporter/assets/24956657/949ded2a-5a20-4a10-abfb-087c00cb816b">
<img width="1665" alt="image" src="https://github.com/zxh326/clash-exporter/assets/24956657/8f570003-2ed0-4e5b-bdf6-61d7335789ba">
<img width="919" alt="image" src="https://github.com/zxh326/clash-exporter/assets/24956657/c5a2d1f2-48fc-411f-a475-f999a60d99c5">

使用 docker compose 部署 并将 clash-exporter 添加 entrypoint: /app/clash-exporter -collectTracing=true 开启收集 
dns 部分正常 下面两个 无数据

**Comment by zxh326** [comment]
> <img alt="image" width="1692" src="https://user-images.githubusercontent.com/24956657/245980958-949ded2a-5a20-4a10-abfb-087c00cb816b.png"> <img alt="image" width="1665" src="https://user-images.githubusercontent.com/24956657/245981010-8f570003-2ed0-4e5b-bdf6-61d7335789ba.png"> <img alt="image" width="919" src="https://user-images.githubusercontent.com/24956657/245981117-c5a2d1f2-48fc-411f-a475-f999a60d99c5.png">
> 使用 docker compose 部署 并将 clash-exporter 添加 entrypoint: /app/clash-exporter -collectTracing=true 开启收集 dns 部分正常 下面两个 无数据

dashboard 是通过 id 导入的吗？我忘了更新了

**Comment by Dark-Existed** [comment]
是的 通过 id 进行导入的

**Comment by zxh326** [comment]
> 是的 通过 id 进行导入的

更新下试试，应该好了

**Comment by Dark-Existed** [comment]
> > 是的 通过 id 进行导入的
> 
> 更新下试试，应该好了

可以了没问题了

**Comment by luckyyyyy** [comment]
it works, thank
