### ISSUE TITLE
grafana 无法连接 prometheus

### ISSUE THREAD

**Issue by fuzhengyin** [zxh326/clash-exporter#4]
<img width="1269" alt="截屏2023-06-26 16 46 28" src="https://github.com/zxh326/clash-exporter/assets/89236842/1440b731-94ef-4eb4-bad3-aab2d91f2354">

除了前面的问题，我在docker 中运行的clash-exporter 会连接不上。release 的连接没有出现错误
>..[$] <()> ./clash-exporter-v0.0.1-darwin-arm64
2023/06/26 16:42:41 Listening on : 2112
2023/06/26 16:42:41 starting collector: connections

**Comment by zxh326** [comment]
datasource 需要去 grafana 设置 中手动加一下

**Comment by fuzhengyin** [comment]
解决了，并且添加prometheus 时需要使用prometheus:9090 访问
clash-exporter 访问宿主机， 在macOs和windows 上需要使用特殊的ip：host.docker.internal
还有一个问题是
>OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknow

连接不上terminal，还是说应该用别的shell

还有一个问题，应该是bug，在docker-compose 中修改collectTrace 为false 不生效，这个应该新开一个issue 吧

**Comment by zxh326** [comment]
>连接不上terminal，还是说应该用别的shell

默认 base 镜像 使用 `scratch` 构建，不含有 shell，如果需要可以自行使用其他 base 镜像构建

> 在docker-compose 中修改collectTrace 为false 不生效

没太懂你的意思，如何改的，怎么个不生效法？

**Comment by fuzhengyin** [comment]
在没有开启tracing 的状态下，把
```yaml
entrypoint:
      ["/app/clash-exporter", "-collectTracing", "true", "-collectDest", "true"]
```
修改成
```yaml
entrypoint:
      ["/app/clash-exporter", "-collectTracing", "false", "-collectDest", "true"]
```
然后启动clash-exporter，log 会出现
https://github.com/zxh326/clash-exporter/blob/d8fab47a0b5b0df13301cbc0bb9fd7e39ad6b951/collector/tracing.go#L52

**Comment by zxh326** [comment]
> 在没有开启tracing 的状态下，把
> 
> ```yaml
> entrypoint:
>       ["/app/clash-exporter", "-collectTracing", "true", "-collectDest", "true"]
> ```
> 
> 修改成
> 
> ```yaml
> entrypoint:
>       ["/app/clash-exporter", "-collectTracing", "false", "-collectDest", "true"]
> ```
> 
> 然后启动clash-exporter，log 会出现
> 
> https://github.com/zxh326/clash-exporter/blob/d8fab47a0b5b0df13301cbc0bb9fd7e39ad6b951/collector/tracing.go#L52

好的，我晚点看一下
