### ISSUE TITLE
高CPU占用

### ISSUE THREAD

**Issue by ZingLix** [zxh326/clash-exporter#8]
运行时发现CPU占用极高，同时带着clash的CPU占用上升

![image](https://github.com/zxh326/clash-exporter/assets/22333469/c48c66bd-dd79-4fc4-9536-ed06df454ac4)

疑似是collector.Start有一个循环不断去收集数据，但该循环在部分情况下没有阻塞在 `c.Collect`，导致循环空转CPU占用极高

- 未开启 collectTracing 时，tracing.Collect 直接返回 nil
- info.Collect 请求版本信息后就返回 nil 了，导致一直在循环请求版本信息，clash本身的CPU占用也因此升高

**Comment by zxh326** [comment]
试试 最新版
